Repository openebs/lvm-localpv, pull requests merged in 2021-05, with the labels that each got.

#64 fix(lints): fix go var name lint errors and add golint in lint workflow
  .github/workflows/pull_request.yml
  pkg/lvm/lvm_util.go
  tests/pv/buildlist.go
  tests/pv/persistentvolume.go
Labels: bug

#81 chore(doc): add Conformance matrix for PVC & SC spec
  docs/persistentvolumeclaim.md
  docs/storageclasses.md
Labels: documentation

#76 fix(prov): add controller to avoid potential volume leaks
  pkg/driver/controller.go
  pkg/mgmt/csipv/leak_protection.go
Labels: pr/community
