Repository openebs/lvm-localpv, pull requests merged in 2021-06, with the labels that each got.

#84 chore(doc): update conformance matrix of SC & PVC
  docs/persistentvolumeclaim.md
  docs/storageclasses.md
Labels: documentation

#92 chore(docs): auto-extend LVM thin pools configuration docs
  docs/thin_provision.md
Labels: documentation

#89 chore(doc): add conformance matrix of csi capabilities
  docs/csi_capability.md
Labels: documentation

#83 chore(expansion): add design proposal for LVM volume expansion
  design/lvm/images/resize_sequence_diagram.jpg
  design/lvm/resize_workflow.md
Labels: design

#99 feat(snapshot): make snapshot size configurable via snapshotclass
  changelogs/unreleased/99-shubham14bajpai
  deploy/lvm-operator.yaml
  deploy/yamls/lvmsnapshot-crd.yaml
  pkg/apis/openebs.io/lvm/v1alpha1/lvmsnapshot.go
  pkg/apis/openebs.io/lvm/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/snapbuilder/build.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/params.go
  pkg/lvm/lvm_util.go
Labels: enhancement

#102 feat(snapshot): add support for thin snapshot for lvm volumes
  pkg/driver/controller.go
  pkg/driver/params.go
  pkg/lvm/lvm_util.go
Labels: enhancement

#109 fix(actions): skip release workflow on helm release
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
Labels: enhancement

#107 Fix bunch of typos
  deploy/helm/charts/Chart.yaml
  deploy/helm/charts/crds/volumesnapshots.yaml
  deploy/helm/charts/values.yaml
  deploy/lvm-operator.yaml
  deploy/yamls/lvm-driver.yaml
Labels: pr/community
