Repository openebs/lvm-localpv, pull requests merged in 2021-03, with the labels that each got.

#19 Workaround to set IOPS, BPS limit for Pod accessing a Volume
  cmd/main.go
  deploy/lvm-operator.yaml
  deploy/yamls/lvm-driver.yaml
  pkg/config/config.go
  pkg/driver/agent.go
  pkg/lvm/iolimiter.go
  pkg/lvm/iolimiter_test.go
  pkg/lvm/mount.go
  vendor/github.com/openebs/lib-csi/pkg/device/iolimit/models.go
  vendor/github.com/openebs/lib-csi/pkg/device/iolimit/utils.go
  vendor/modules.txt
Labels: pr/community

#24 feat(e2e-tests): Add e2e-test for lvm-localpv
  .travis.yml
  Makefile
  e2e-tests/Dockerfile
  e2e-tests/apps/busybox/deployers/busybox_deployment.yml
  e2e-tests/apps/busybox/deployers/busybox_statefulset.yml
  e2e-tests/apps/busybox/deployers/run_litmus_test.yml
  e2e-tests/apps/busybox/deployers/test.yml
  e2e-tests/apps/busybox/deployers/test_vars.yml
  e2e-tests/apps/busybox/liveness/busybox_liveness.yml
  e2e-tests/apps/busybox/liveness/run_litmus_test.yml
  e2e-tests/apps/busybox/liveness/test.yml
  e2e-tests/apps/busybox/liveness/test_vars.yml
  e2e-tests/apps/percona/deployers/percona.yml
  e2e-tests/apps/percona/deployers/run_litmus_test.yml
  e2e-tests/apps/percona/deployers/test.yml
  e2e-tests/apps/percona/deployers/test_vars.yml
  e2e-tests/apps/percona/workload/replace.yml
  e2e-tests/apps/percona/workload/run_litmus_test.yml
  e2e-tests/apps/percona/workload/test.yml
  e2e-tests/apps/percona/workload/test_vars.yml
  e2e-tests/apps/percona/workload/tpcc.conf
  e2e-tests/apps/percona/workload/tpcc_bench.yml
  e2e-tests/experiments/lvm-localpv-provisioner/run_litmus_test.yml
  e2e-tests/experiments/lvm-localpv-provisioner/test.yml
  e2e-tests/experiments/lvm-localpv-provisioner/test_vars.yml
  e2e-tests/hack/crds.yaml
  e2e-tests/hack/create_testname.yml
  e2e-tests/hack/litmus-result.j2
  e2e-tests/hack/push
  e2e-tests/hack/rbac.yaml
  e2e-tests/hack/update_litmus_result_resource.yml
  e2e-tests/utils/applications/busybox/busybox_data_persistence.yml
  e2e-tests/utils/applications/mysql/check_db_connection.yml
  e2e-tests/utils/applications/mysql/mysql_data_persistence.yml
  e2e-tests/utils/k8s/create_ns.yml
  e2e-tests/utils/k8s/deploy_single_app.yml
  e2e-tests/utils/k8s/deprovision_deployment.yml
  e2e-tests/utils/k8s/deprovision_statefulset.yml
  e2e-tests/utils/k8s/fetch_app_pod.yml
  e2e-tests/utils/k8s/pre_create_app_deploy.yml
  e2e-tests/utils/k8s/status_app_pod.yml
  e2e-tests/utils/k8s/status_testns.yml
Labels: feature

#23 feat(provisioning) enable pod resheduling cause of node insufficient capacity
  deploy/lvm-operator.yaml
  deploy/yamls/lvmvolume-crd.yaml
  pkg/apis/openebs.io/lvm/v1alpha1/lvmvolume.go
  pkg/apis/openebs.io/lvm/v1alpha1/zz_generated.deepcopy.go
  pkg/driver/controller.go
  pkg/driver/params.go
  pkg/driver/schd_helper.go
  pkg/lvm/lvm_util.go
  pkg/lvm/volume.go
  pkg/mgmt/volume/volume.go
Labels: pr/community

#32 feat(e2e-test): Add e2e-test for lvm volume resize support
  e2e-tests/experiments/functional/lvm-volume-resize/README.md
  e2e-tests/experiments/functional/lvm-volume-resize/run_e2e_test.yml
  e2e-tests/experiments/functional/lvm-volume-resize/test.yml
  e2e-tests/experiments/functional/lvm-volume-resize/test_vars.yml
Labels: e2e/lvm-localpv

#21 feat(scheduling): add volume group capacity tracking
  buildscripts/generate-manifests.sh
  deploy/lvm-operator.yaml
  deploy/yamls/lvm-driver.yaml
  deploy/yamls/lvmnode-crd.yaml
  pkg/apis/openebs.io/lvm/v1alpha1/lvmnode.go
  pkg/apis/openebs.io/lvm/v1alpha1/register.go
  pkg/apis/openebs.io/lvm/v1alpha1/zz_generated.deepcopy.go
  pkg/builder/nodebuilder/kubernetes.go
  pkg/builder/nodebuilder/node.go
  pkg/driver/agent.go
  pkg/driver/controller.go
  pkg/equality/semantic.go
  pkg/generated/clientset/internalclientset/typed/lvm/v1alpha1/fake/fake_lvm_client.go
  pkg/generated/clientset/internalclientset/typed/lvm/v1alpha1/fake/fake_lvmnode.go
  pkg/generated/clientset/internalclientset/typed/lvm/v1alpha1/generated_expansion.go
  pkg/generated/clientset/internalclientset/typed/lvm/v1alpha1/lvm_client.go
  pkg/generated/clientset/internalclientset/typed/lvm/v1alpha1/lvmnode.go
  pkg/generated/informer/externalversions/generic.go
  pkg/generated/informer/externalversions/lvm/v1alpha1/interface.go
  pkg/generated/informer/externalversions/lvm/v1alpha1/lvmnode.go
  pkg/generated/lister/lvm/v1alpha1/expansion_generated.go
  pkg/generated/lister/lvm/v1alpha1/lvmnode.go
  pkg/lvm/lvm_util.go
  pkg/mgmt/lvmnode/builder.go
  pkg/mgmt/lvmnode/lvmnode.go
  pkg/mgmt/lvmnode/start.go
Labels: pr/community

#36 chore(doc): adding provisioning/deprovisioning, resize and raw block doc
  README.md
  docs/raw-block-volume.md
  docs/resize.md
Labels: documentation

#35 chore(changelog): adding v0.3.0 changelog
  CHANGELOG.md
  changelogs/released/v0.3.0/19-abhranilc
  changelogs/released/v0.3.0/21-iyashu
  changelogs/released/v0.3.0/23-iyashu
  changelogs/released/v0.3.0/24-w3aman
  changelogs/released/v0.3.0/25-pawanpraka1
  changelogs/released/v0.3.0/26-pawanpraka1
  changelogs/released/v0.3.0/27-pawanpraka1
  changelogs/released/v0.3.0/29-w3aman
  changelogs/released/v0.3.0/32-w3aman
Labels: documentation
